name: "Format Code: ensure code formatting guidelines are met"
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: write
  security-events: write  # needed for SARIF upload
  
jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: format-code
        uses: ministryofjustice/modernisation-platform-github-actions/format-code@e3ccf33927794ce5350b9211e288ad84e69365a8 # v3.4.4

  commit-fixes:
    runs-on: ubuntu-latest
    steps:
      - name: commit-changes
        uses: ministryofjustice/modernisation-platform-github-actions/signed-commit@e3ccf33927794ce5350b9211e288ad84e69365a8 # v3.4.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "GitHub Actions Code Formatter workflow"
          pr_body: "This pull request includes updates from the GitHub Actions Code Formatter workflow. Please review the changes and merge if everything looks good."
