name: Prek checks
on: pull_request
jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.2
      - uses: j178/prek-action@v1.0.11
